### PR TITLE
Added Settings -> Collect option in menu to run collect.sh

### PR DESCRIPTION
**Pull request by AnirbanBanik1998**
Improved the meme_gui_support.py and meme_gui.py so that it runs the collect.sh from within the program

### CODE REVIEW

**Comment by Aniq55** [comment]
Please add screenshots

**Comment by AnirbanBanik1998** [comment]
screenshot from 2018-02-03 01-35-29

**Comment by AnirbanBanik1998** [comment]
screenshot from 2018-02-03 01-36-16

When I click on Settings

**Comment by AnirbanBanik1998** [comment]
screenshot from 2018-02-03 01-38-36

New temp.sh after adding the names of subreddits as arguments

**Comment by Aniq55** [comment]
Looks fine. There is a problem. I want it to be a menu option, not a button. And from that drop down you select add subreddit. Like you code Open from File and New from file, similarly it should be "Add subreddit" when you select the "Settings" option from the menu. You only require to change the design

**Comment by AnirbanBanik1998** [comment]
Ok...no problem...I will work on it🙂

**Comment by Aniq55** [comment]
Ref #14

**Comment by AnirbanBanik1998** [comment]
Improvements made

**Pull request merged**
