### PR TITLE
Create 'Dank' logo

### PR DESCRIPTION
**Pull request by khyati18**
Svg file of the Dank Logo .

### CODE REVIEW

**Comment by Aniq55** [comment]
@khyati18 no need to upload the SVG here, a good quality png would do. Also, put that png inside a `misc` folder.

**Comment by khyati18** [comment]
How to add the png file? I am not getting it .

**Comment by Aniq55** [comment]
1. Save the SVG as PNG
2. create a folder called `misc`
3. put the PNG file inside this `misc` folder
4. add the `PNG` file, commit and push

@khyati18

**Comment by khyati18** [comment]
50218701-d559b980-03b2-11e9-9b11-437709704c0c

Here is the png file

**Pull request closed without merging**
