### PR TITLE
Add requests to requirements.txt and style to PEP8

### PR DESCRIPTION
**Pull request by vixrant**
I was finding it difficult to read the code so I ran autopep8 on the py files.

### CODE REVIEW

**Comment by Aniq55** [comment]
@vixrant The code is running perfectly, right? I seriously don't have the time to review the whole project at once.

**Comment by vixrant** [comment]
`meme_gui.py` works like before:

ss

Tkinter is buggy on MacOS Mojave so it doesn't show the buttons text unless I push them.

**Comment by Aniq55** [comment]
Alright. Would you like to fix it in your next PR? (optional). I'm merging this for now, good work!

**Comment by vixrant** [comment]
I'm working on the flask app actually... I went through the source code once to see how everything works. I don't like working with Tkinter 😅 Besides this is a MacOS problem: https://trac.macports.org/ticket/57357

**Pull request merged**
